services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: my-url-matching-postgres

volumes:
  db_data: